# Generated by Django 5.0.4 on 2024-04-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='albom',
            new_name='album',
        ),
    ]
